#include <iostream>
#include <string>

template <typename T>
class NamedObject
{
public:
    NamedObject(const char* name, const T& value) : theName{name}, theObject{value} {}
    NamedObject(std::string name, const T& value) : theName{name}, theObject{value} {}
    
private:
    std::string theName;
    T theObject;
};

// no copy constructor or copy assignment defined, 
// so these will be automatically generated by the compiler if needed
// if there is at least one constructor, 
// then no default constructor will be defined by the compiler

int main()
{
 NamedObject<int> p("Olive",10);
 NamedObject<int> s("Freddie",11);
 p = s; // copy assignment will be generated by the compiler.
}